import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Tina's generated files: the static admin SPA build (minified
    // third-party bundles that crash ESLint's parser on size) and the
    // GraphQL client/types/schema regenerated by `tinacms dev`/`build`.
    "public/admin/**",
    "tina/__generated__/**",
  ]),
]);

export default eslintConfig;
